# Generated by Django 2.1 on 2019-08-06 04:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=15, verbose_name='Title')),
                ('text', models.TextField(max_length=200, verbose_name='Text')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date')),
            ],
        ),
    ]
